apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ .Values.nsName }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.backend.postgresUser | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.backend.postgresPassword | b64enc }}
