apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.nsName }}
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  type: ClusterIP
