apiVersion: v1
kind: Service
metadata:
    name: frontend
    namespace: task-manager
    labels:
        app: frontend
spec:
    selector:
        app: frontend
    ports:
        - port: 80
          targetPort: 80
          nodePort: 30080
          name: http
    type: NodePort
