apiVersion: v2
name: task-manager-helm
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: "1.16.0"

# Dependencies section
dependencies:
  - name: ingress-nginx
    version: "4.6.0"
    repository: "https://kubernetes.github.io/ingress-nginx"
