apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: task-manager
  labels:
    app: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      # securityContext:
      #   runAsNonRoot: true
      #   runAsUser: 999
      #   runAsGroup: 999
      #   fsGroup: 999
      #   seccompProfile:
      #     type: RuntimeDefault
      initContainers:
      - name: give-permission
        image: busybox:1.35.0-uclibc
        command:
        - sh
        - -c
        - "chmod 700 /var/lib/postgresql/data && chown -R 999:999 /var/lib/postgresql/data"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      terminationGracePeriodSeconds: 60
      containers:
      - name: postgres
        image: postgres:14-alpine
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 999
          runAsGroup: 999
          capabilities:
            drop:
            - ALL
            add:
            - CHOWN
            - FOWNER
            - SETGID
            - SETUID
        ports:
        - containerPort: 5432
          name: postgres
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        envFrom:
        - configMapRef:
            name: postgres-config
        - secretRef:
            name: postgres-secret
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready -U $POSTGRES_USER
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready -U $POSTGRES_USER
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
